import { ACTIVITY_TYPE_ENUM } from "../../types/constants/activity.js";
import { USER_LEVEL_ENUM } from "../../types/constants/profile.js";

export const ACTIVITY_TYPE_SPECIAL = [
    ACTIVITY_TYPE_ENUM.SSC,
    ACTIVITY_TYPE_ENUM.KK,
    ACTIVITY_TYPE_ENUM.LMD,
    ACTIVITY_TYPE_ENUM.INVENTRA,
    ACTIVITY_TYPE_ENUM.KOMPROF,
    ACTIVITY_TYPE_ENUM.SPECTRA,
]

export const ACTIVITY_LEVEL_UPGRADE_MAP = {
    [ACTIVITY_TYPE_ENUM.SSC]: USER_LEVEL_ENUM.AKTIVIS,
    [ACTIVITY_TYPE_ENUM.KK]: USER_LEVEL_ENUM.AKTIVIS_KK,
    [ACTIVITY_TYPE_ENUM.LMD]: USER_LEVEL_ENUM.KADER,
    [ACTIVITY_TYPE_ENUM.INVENTRA]: USER_LEVEL_ENUM.KADER_INVENTRA,
    [ACTIVITY_TYPE_ENUM.KOMPROF]: USER_LEVEL_ENUM.KADER_KOMPROF,
    [ACTIVITY_TYPE_ENUM.SPECTRA]: USER_LEVEL_ENUM.KADER_LANJUT,
}